import "./global.scss";
import ServerNav from "./server-nav";
import { Analytics } from "@vercel/analytics/react";
import Header from "@/components/header";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
   title: "C.O Portfolio",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="fr">
         <head>
            <link rel="shortcut icon" href="/fav.ico" type="image/x-icon" />
         </head>
         <body className="w-full">
            <ServerNav>
               <Header />
               {children}
            </ServerNav>
            <Analytics />
            <SpeedInsights />
         </body>
      </html>
   );
}
